name: API login com secutiry-JWT-auth0

on:
 push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set JWT expiration environment variable
      run: echo "jwt.expiration=604800000" >> $GITHUB_ENV
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
